const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');

(async () => {
  const browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || 'chrome' });
  try {
    const context = await browser.newContext({ viewport: { width: 1600, height: 1100 } });
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(process.env.CUBE_URL || 'http://127.0.0.1:8766');
    const ids = await page.locator('[data-card]').evaluateAll(nodes => nodes.map(node => node.dataset.card));
    assert.equal(ids.length, 180);
    assert.equal(new Set(ids).size, 180);
    assert.equal(await page.locator('.group').count(), 29);
    await page.locator('.art img').evaluateAll(images => images.forEach(image => image.loading = 'eager'));
    await page.waitForFunction(() => [...document.querySelectorAll('.art img')].every(img => img.complete && img.naturalWidth > 0));
    const check = id => page.locator(`[data-card="${id}"]`);
    const seed = async values => {
      await page.evaluate(values => localStorage.setItem('cube-atlas.progress.v1', JSON.stringify({ version: 1, included: values })), values);
      await page.reload();
      assert.equal(await page.locator('#toast').isVisible(), false, 'No celebration on reload');
    };
    await check(ids[0]).check();
    assert.equal(await check(ids[1]).isChecked(), false, 'Card checkboxes are independent');
    assert.equal(await page.locator('#percentage').innerText(), '0.6%');
    await page.reload();
    assert.equal(await check(ids[0]).isChecked(), true, 'Progress survives reload');
    const secondTab = await context.newPage();
    await secondTab.goto(page.url());
    await check(ids[1]).check();
    await secondTab.waitForFunction(() => document.querySelectorAll('input:checked').length === 2);
    await secondTab.close();
    await page.getByLabel('Find a card').fill('felidar');
    assert.equal(await page.locator('.card:visible').count(), 2);
    await page.getByLabel('Filter by color').selectOption('blue');
    assert.equal(await page.locator('#empty').isVisible(), true);
    await page.getByLabel('Find a card').fill('');
    assert.equal(await page.locator('.card:visible').count(), 25);
    await page.getByLabel('Filter by color').selectOption('all');
    await page.locator('[data-filter="included"]').click();
    assert.equal(await page.locator('.card:visible').count(), 2);
    await check(ids[0]).uncheck();
    assert.equal(await page.locator('.card:visible').count(), 1);
    assert.equal(await check(ids[1]).evaluate(node => node === document.activeElement), true);
    await page.locator('[data-filter="missing"]').click();
    assert.equal(await page.locator('.card:visible').count(), 179);
    const white = ids.filter(id => id.startsWith('white:'));
    await seed(white.slice(0, 2));
    await check(white[2]).check();
    assert.equal(await page.locator('#toast-title').textContent(), 'White · Common complete!');
    assert.ok(await page.locator('.particle').count() > 0);
    assert.equal(await page.locator('.group[data-complete="true"]').count(), 1);
    await seed(white.slice(0, -1));
    await check(white.at(-1)).check();
    assert.equal(await page.locator('#toast-title').textContent(), 'White, all together.');
    assert.equal(await page.locator('.column[data-complete="true"]').count(), 1);
    await seed(ids.slice(0, -1));
    assert.equal(await page.locator('#percentage').innerText(), '99.4%');
    await check(ids.at(-1)).check();
    assert.equal(await page.locator('#toast-title').textContent(), 'Your cube is complete!');
    assert.equal(await page.locator('#percentage').innerText(), '100%');
    assert.equal(await page.locator('#cube-celebration').isVisible(), true);
    assert.equal(await page.locator('.column[data-complete="true"]').count(), 8);
    assert.equal(await page.locator('.group[data-complete="true"]').count(), 29);
    await check(ids.at(-1)).uncheck();
    assert.equal(await page.locator('#percentage').innerText(), '99.4%');
    assert.equal(await page.locator('.column[data-complete="true"]').count(), 7);
    await seed([ids[0], ids[1]]);
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Back up progress' }).click();
    const download = await downloadPromise;
    const fs = require('node:fs/promises');
    const backup = JSON.parse(await fs.readFile(await download.path(), 'utf8'));
    assert.deepEqual(backup.included, ids.slice(0, 2));
    page.once('dialog', dialog => dialog.accept());
    await page.locator('#restore-file').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({version: 1, included: ids.slice(0, 5)})) });
    await page.waitForFunction(() => document.querySelectorAll('input:checked').length === 5);
    await page.locator('#restore-file').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"version":1,"included":["wrong"]}') });
    await page.waitForFunction(() => document.querySelector('#toast-title').textContent === 'That backup could not be read.');
    assert.equal(await page.locator('input:checked').count(), 5);
    await seed(white.slice(0, 2));
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await check(white[2]).check();
    assert.equal(await page.locator('#toast-title').textContent(), 'White · Common complete!');
    assert.equal(await page.locator('.particle').count(), 0, 'Reduced motion suppresses particles');
    await page.emulateMedia({ reducedMotion: 'no-preference' });
    await seed([]);
    for (const width of [320, 390, 768, 1280, 1600]) {
      await page.setViewportSize({ width, height: 900 });
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `No horizontal overflow at ${width}px`);
    }
    await page.locator('.art img').evaluateAll(images => images.forEach(image => image.loading = 'eager'));
    await page.waitForFunction(() => [...document.querySelectorAll('.art img')].every(img => img.complete && img.naturalWidth > 0));
    await page.screenshot({ path: '/tmp/cube-atlas-desktop-final.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.screenshot({ path: '/tmp/cube-atlas-mobile-final.png' });
    await page.getByLabel('Filter by color').selectOption('lands');
    assert.equal(await page.locator('.card:visible').count(), 23);
    await page.getByRole('checkbox', { name: 'Include Bloodfell Caves', exact: true }).focus();
    await page.keyboard.press('Space');
    assert.equal(await page.getByRole('checkbox', { name: 'Include Bloodfell Caves', exact: true }).isChecked(), true);
    const blocked = await browser.newContext();
    await blocked.addInitScript(() => {
      Storage.prototype.setItem = () => { throw new DOMException('Full', 'QuotaExceededError'); };
    });
    const blockedPage = await blocked.newPage();
    await blockedPage.goto(page.url());
    await blockedPage.getByRole('checkbox').first().check();
    assert.equal(await blockedPage.locator('#storage-error').isVisible(), true);
    assert.equal(await blockedPage.getByRole('checkbox').first().isChecked(), true);
    await blocked.close();
    await page.evaluate(() => localStorage.setItem('cube-atlas.progress.v1', 'corrupted'));
    await page.reload();
    assert.equal(await page.locator('#storage-error').isVisible(), true);
    await page.getByRole('checkbox').first().check();
    assert.equal(await page.evaluate(() => localStorage.getItem('cube-atlas.progress.v1')), 'corrupted');
    assert.deepEqual(errors, []);
    console.log('PASS: 180 independent slots, all art, persistence, cross-tab updates, filters, keyboard, all 3 celebrations, undo, backup/restore, reduced motion, 5 viewport widths, and storage failures.');
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
